name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install tailwindcss postcss autoprefixer
      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./src/input.css -o ./src/output.css --minify
      - name: Inject API Key
        env:
          TIMEZONEDB_API_KEY: ${{ secrets.TIMEZONEDB_API_KEY }}
        run: sed -i "s/const TIMEZONEDB_API_KEY = 'YOUR_API_KEY';/const TIMEZONEDB_API_KEY = '$TIMEZONEDB_API_KEY';/" index.html
      - name: Show index.html after replacement
        run: head -n 45 index.html
      - name: Copy src directory to publish directory
        run: |
          mkdir -p ./publish/src
          cp -r ./src/output.css ./publish/src/
          cp index.html ./publish/
          cp favicon.ico ./publish/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages